from abc import ABC, abstractmethod
from typing import Any, Optional, Dict, List


class AbstractDrafter(ABC):
    """
    Abstract base class representing the Draft Model in speculative decoding.
    The Drafter generates a small sequence of speculative tokens (guesses) 
    based on the current prefix sequence.
    """

    @abstractmethod
    def generate_draft(self, prompt: List[int]) -> List[int]:
        """
        Generate speculative token guesses for the next words/tokens.

        Args:
            prompt: List of token IDs representing the current prefix context.

        Returns:
            A list of guessed token IDs (draft tokens).
        """
        pass


class AbstractVerifier(ABC):
    """
    Abstract base class representing the Verifier (Target Model / Ground Truth reference).
    It compares the drafted tokens against the ground truth sequence in a greedy manner.
    """

    @abstractmethod
    def verify(
        self,
        draft_tokens: List[int],
        current_prefix: List[int],
        complete_tokens: List[int],
    ) -> Dict[str, Any]:
        """
        Greedily compare speculative draft tokens with the ground-truth complete tokens.

        Args:
            draft_tokens: List of speculative token IDs generated by the drafter.
            current_prefix: List of token IDs representing the sequence accepted/generated so far.
            complete_tokens: List of all ground truth token IDs representing the entire final sequence.

        Returns:
            A dictionary containing verification metrics and results:
            {
                "accepted_tokens": List[int],  # The sequence of accepted draft tokens + 1 recovery token
                "accepted_count": int,         # Number of draft tokens accepted
                "rejected_count": int          # Number of draft tokens rejected
            }
        """
        pass


class AbstractPlayback(ABC):
    """
    Abstract base class controlling the execution loop of the speculative decoding simulator.
    Coordinates the interaction between the Drafter, Verifier, Tokenizer, and Metrics tracker.
    """

    def __init__(
        self,
        tokenizer: Any,
        drafter: AbstractDrafter,
        verifier: AbstractVerifier,
        metrics: Optional[Any] = None,
    ) -> None:
        """
        Initialize the Speculate Decoding Playback simulator with Dependency Injection.

        Args:
            tokenizer: Any tokenizer object (e.g. from Qwen 3.5, Gemma 2, HuggingFace, etc. using Duck Typing).
            drafter: An instance of a class derived from AbstractDrafter.
            verifier: An instance of a class derived from AbstractVerifier.
            metrics: Optional metrics tracker, defaults to None (disabled).
        """
        self.tokenizer = tokenizer
        self.drafter = drafter
        self.verifier = verifier
        self.metrics = metrics

    @abstractmethod
    def run_playback(self, input_data: str, use_drafter: bool = True) -> str:
        """
        Run the token-by-token decoding playback simulation.

        Args:
            input_data: The prompt string to start the generation or verification process.
            use_drafter: Flag to toggle whether the Speculative Drafter should be utilized.

        Returns:
            The final decoded output string.
        """
        pass
