"""Abstract base class for the Verifier (Target Model) in speculative decoding."""
from abc import ABC, abstractmethod
from typing import Dict, List


class AbstractVerifier(ABC):
    """
    Abstract base class representing the Verifier (Target Model / Ground Truth reference).

    Compares the drafted tokens against the ground truth sequence in a greedy manner.
    """

    @abstractmethod
    def verify(
        self,
        draft_tokens: List[int],
        current_prefix: List[int],
        complete_tokens: List[int],
    ) -> Dict[str, object]:
        """
        Greedily compare speculative draft tokens with the ground-truth complete tokens.

        Args:
            draft_tokens: List of speculative token IDs generated by the drafter.
            current_prefix: List of token IDs representing the sequence accepted/generated
                so far.
            complete_tokens: List of all ground truth token IDs representing the entire
                final sequence.

        Returns:
            A dictionary containing verification metrics and results:
            {
                "accepted_tokens": List[int],  # accepted draft tokens + 1 recovery token
                "accepted_count": int,         # number of draft tokens accepted
                "rejected_count": int,         # number of draft tokens rejected
            }
        """
