from abc import ABC, abstractmethod
from typing import TYPE_CHECKING, Any, Optional, Dict, List

if TYPE_CHECKING:
    import torch


class AbstractDrafter(ABC):
    """
    Abstract base class representing the Draft Model in speculative decoding.
    The Drafter generates a small sequence of speculative tokens (guesses) 
    based on the current prefix sequence.
    """

    @abstractmethod
    def generate_draft(self, prompt: List[int]) -> List[int]:
        """
        Generate speculative token guesses for the next words/tokens.

        Args:
            prompt: List of token IDs representing the current prefix context.

        Returns:
            A list of guessed token IDs (draft tokens).
        """
        pass


class AbstractVerifier(ABC):
    """
    Abstract base class representing the Verifier (Target Model / Ground Truth reference).
    It compares the drafted tokens against the ground truth sequence in a greedy manner.
    """

    @abstractmethod
    def verify(
        self,
        draft_tokens: List[int],
        current_prefix: List[int],
        complete_tokens: List[int],
    ) -> Dict[str, Any]:
        """
        Greedily compare speculative draft tokens with the ground-truth complete tokens.

        Args:
            draft_tokens: List of speculative token IDs generated by the drafter.
            current_prefix: List of token IDs representing the sequence accepted/generated so far.
            complete_tokens: List of all ground truth token IDs representing the entire final sequence.

        Returns:
            A dictionary containing verification metrics and results:
            {
                "accepted_tokens": List[int],  # The sequence of accepted draft tokens + 1 recovery token
                "accepted_count": int,         # Number of draft tokens accepted
                "rejected_count": int          # Number of draft tokens rejected
            }
        """
        pass


class AbstractPlayback(ABC):
    """
    Abstract base class controlling the execution loop of the speculative decoding simulator.
    Coordinates the interaction between the Drafter, Verifier, Tokenizer, and Metrics tracker.
    """

    def __init__(
        self,
        tokenizer: Any,
        drafter: AbstractDrafter,
        verifier: AbstractVerifier,
        metrics: Optional[Any] = None,
    ) -> None:
        """
        Initialize the Speculate Decoding Playback simulator with Dependency Injection.

        Args:
            tokenizer: Any tokenizer object (e.g. from Qwen 3.5, Gemma 2, HuggingFace, etc. using Duck Typing).
            drafter: An instance of a class derived from AbstractDrafter.
            verifier: An instance of a class derived from AbstractVerifier.
            metrics: Optional metrics tracker, defaults to None (disabled).
        """
        self.tokenizer = tokenizer
        self.drafter = drafter
        self.verifier = verifier
        self.metrics = metrics

    @abstractmethod
    def run_playback(self, input_data: str, use_drafter: bool = True) -> str:
        """
        Run the token-by-token decoding playback simulation.

        Args:
            input_data: The prompt string to start the generation or verification process.
            use_drafter: Flag to toggle whether the Speculative Drafter should be utilized.

        Returns:
            The final decoded output string.
        """
        pass


class AbstractTensorDrafter(ABC):
    """
    Tensor-based counterpart of AbstractDrafter for batched speculative decoding.

    Instead of a single ``List[int]`` sequence, the drafter returns a 2D tensor of
    shape ``[S, T]`` (S candidate sequences, each of depth T). This naturally covers
    both strategies under a fixed token budget B:
        - depth-draft:  one long bet      -> S=1, T=B   -> shape [1, B]
        - width-draft:  several short bets -> S>1, T<B  -> shape [S, T] (S*T <= B)
    """

    @abstractmethod
    def generate_draft(self, prompt: List[int]) -> "torch.Tensor":
        """
        Generate speculative token guesses as a 2D tensor.

        Args:
            prompt: List of token IDs representing the current prefix context.

        Returns:
            A ``torch.long`` tensor of shape ``[S, T]``. Rows shorter than T are
            right-padded with the PAD sentinel ``-1``. When no match is found an
            empty tensor of shape ``[0, 0]`` is returned.
        """
        pass


class AbstractTensorVerifier(ABC):
    """
    Tensor-based counterpart of AbstractVerifier.

    Accepts a batch of candidate draft sequences (shape ``[S, T]``), greedily
    verifies every candidate against the ground-truth sequence, and keeps only the
    single candidate whose prefix matches the ground truth for the longest run.
    """

    @abstractmethod
    def verify(
        self,
        draft_tokens: "torch.Tensor",
        current_prefix: List[int],
        complete_tokens: List[int],
    ) -> Dict[str, Any]:
        """
        Greedily verify a batch of speculative draft sequences against ground truth.

        Args:
            draft_tokens: ``torch.long`` tensor of shape ``[S, T]`` (PAD = -1).
            current_prefix: Token IDs accepted/generated so far.
            complete_tokens: All ground-truth token IDs for the final sequence.

        Returns:
            {
                "accepted_tokens": List[int],  # winning candidate prefix + 1 recovery token
                "accepted_count": int,         # draft tokens accepted from the winner
                "rejected_count": int,         # remaining (unaccepted) tokens in the winner
                "chosen_sequence": int,        # row index of the winning candidate (-1 if none)
            }
        """
        pass
